import { CommitInfo, CommitGroup } from './git';
import { format as formatDate } from 'date-fns';

/**
 * Export a daily summary as Markdown.
 */
export function exportDailyMarkdown(
  repoName: string,
  date: string,
  commits: CommitInfo[],
  aiSummary: string
): string {
  let md = `# Developer Journal: ${repoName}\n`;
  md += `**Date**: ${date}\n\n`;

  if (aiSummary) {
    md += `## Summary\n\n${aiSummary}\n\n`;
  }

  md += `## Commits (${commits.length})\n\n`;
  for (const commit of commits) {
    md += `- \`${commit.hashShort}\` ${commit.message}`;
    if (commit.filesChanged.length > 0) {
      md += ` _(${commit.filesChanged.length} files)_`;
    }
    md += '\n';
  }

  md += `\n---\n_Generated by [devlog](https://github.com/devlog-cli/devlog) — Powered by GitHub Copilot CLI_\n`;
  return md;
}

/**
 * Export a weekly summary as Markdown.
 */
export function exportWeeklyMarkdown(
  repoName: string,
  groups: CommitGroup[],
  aiSummary: string,
  totalCommits: number
): string {
  let md = `# Weekly Recap: ${repoName}\n`;
  md += `**Week of**: ${formatDate(new Date(), 'MMMM d, yyyy')}\n`;
  md += `**Total commits**: ${totalCommits}\n\n`;

  if (aiSummary) {
    md += `## Highlights\n\n${aiSummary}\n\n`;
  }

  md += `## Daily Breakdown\n\n`;
  for (const group of groups) {
    md += `### ${group.label} (${group.commits.length} commits)\n\n`;
    for (const commit of group.commits) {
      md += `- \`${commit.hashShort}\` ${commit.message}\n`;
    }
    md += '\n';
  }

  md += `---\n_Generated by [devlog](https://github.com/devlog-cli/devlog) — Powered by GitHub Copilot CLI_\n`;
  return md;
}

/**
 * Export release notes as Markdown.
 */
export function exportReleaseMarkdown(
  repoName: string,
  tag: string,
  commits: CommitInfo[],
  aiSummary: string
): string {
  let md = `# Release Notes: ${repoName}\n`;
  md += `**Since**: ${tag}\n`;
  md += `**Commits**: ${commits.length}\n\n`;

  if (aiSummary) {
    md += aiSummary + '\n\n';
  }

  md += `## All Commits\n\n`;
  for (const commit of commits) {
    md += `- \`${commit.hashShort}\` ${commit.message} — _${commit.author}_\n`;
  }

  md += `\n---\n_Generated by [devlog](https://github.com/devlog-cli/devlog) — Powered by GitHub Copilot CLI_\n`;
  return md;
}

/**
 * Export commits as JSON.
 */
export function exportJSON(
  data: Record<string, unknown>
): string {
  return JSON.stringify(data, null, 2);
}
